### ISSUE TITLE
Rest client 1.2-m1

### ISSUE THREAD

**Issue by pavolloffay** [smallrye/smallrye-rest-client#43]
I am working on OpenTracing instrumentation for rest-client 1.2. To verify the integration I would like to run TCK but I need rest-client implementation based on 1.2-m1 https://github.com/eclipse/microprofile-rest-client/releases/tag/1.2-m1.

Is anybody working on the implementation? When it's going to be done?

**Comment by kenfinnigan** [comment]
@michalszynkiewicz has started working on an implementation, but we don't have a deadline yet

**Comment by michalszynkiewicz** [comment]
@pavolloffay most of the features are already implemented in this PR: https://github.com/smallrye/smallrye-rest-client/pull/44
One difficulty to work with it might be that it uses a snapshot version of MP Rest Client (because I'm also solving some TCK issues while working on it). I have passing the method in request context left to implement, when I do that I will create a proper PR.

**Comment by pavolloffay** [comment]
thanks @michalszynkiewicz  I will try it out at the end of this week.
